name: Atualizar Tips do Dia

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Executar o script de geração
        run: node gerar_tips.cjs

      - name: Commit e Push do novo index.html
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.html
          git commit -m "Atualização automática das dicas do dia" || echo "Nada para commitar"
          git push
